name: 🛎️ reset repo before test
on:
  workflow_dispatch:

jobs:
  reset:
    name: commit fix to reset repo
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GH_AUTOMATION_TOKEN }} 
          fetch-depth: 0

      - name: configure git
        run: |
          git config user.name "cangulo-actions-reset-repo[bot]"
          git config user.email "cangulo-actions-reset-repo[bot]@users.noreply.github.com"

      - name: delete all the remote tags
        run: |
          echo "tags:"
          git ls-remote --tags origin 

          remote_tags=($(git ls-remote --tags origin | awk '{print $2}' | awk -F"/" '{print $3}' | sed 's/\^{}//'))
          for tag in "${remote_tags[@]}"
          do
            echo "deleting remote tag ${tag}"
            git push origin --delete "${tag}"
          done

      - name: delete all the GH releases
        env:
          GH_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
        run: |
          gh_releases=($(gh release list | awk '{print $1}'))
          for release in "${gh_releases[@]}"
          do
            echo "deleting release ${release}"
            gh release delete "${release}" --yes
          done
          
      - name: reset files
        run: |
          # delete version.json and CHANGELOG.md if exists
          
          git rm -f version.json CHANGELOG.md || true
          scope_folders=( "src" "terraform" )
          for folder in "${scope_folders[@]}"
          do
            # delete version and CHANGELOG.md
            git rm -f "${folder}/version.json" "${folder}/CHANGELOG.md" || true
          done

      - name: commit changes
        run: |
          git commit -a -m "RESET REPO [SKIP]"
          git push origin main
